### ISSUE TITLE
How to verify compilation speed up?

### ISSUE THREAD

**Issue by kirillt** [cuzfrog/sbt-tmpfs#3]
Hi, I just found this project and immediately decided to try.
I cloned this project https://github.com/unibas-gravis/scalismo, built it to download all dependencies.
Then I rebuilt it with this command:
> $ sbt clean compile

This took 34 seconds on my machine.
Then I set up tmpfs at /tmp, added sbt-tmpfs into project/plugins.sbt and ran this command again.
> $ sbt clean compile

This gave 34 seconds again.
I verified that compiler output is inside /tmp:
> $ ls /tmp/sbttmpfs/
> sbt_27b42856  sbt_bdebd5f4

So, should this plugin boost compilations from scratch or only incremental ones?
How to measure the boost?

**Comment by cuzfrog** [comment]
Hello, the plugin does not maintain a build cache in memory.
By default, it directs the output of the build to tmpfs, thus no writing on disk. But a clean build still needs to read all source code that resided on disk. It speeds up reading when the "build source" can be mapped to the memory, like a `node_modules` dir. The compilation part which requires computation power cannot be speeded, also is not related to this plugin.

**Comment by kirillt** [comment]
Ok, I got part about compilation and this makes sense now, because I guess that compilation is CPU-bound. But which scenarios of development are boosted if I use pure Scala?

**Comment by cuzfrog** [comment]
For me, knowing writing is made on RAM, I do `clean` without hesitation.
