### ISSUE TITLE
How to disable tmpfs compilation?

### ISSUE THREAD

**Issue by arbitrary-dev** [cuzfrog/sbt-tmpfs#5]
## Things tried

1. `sbt clean`
1. Disabling sbt-tmpfs plugin
1. `rm -rf **/target`
1. `sbt clean`

## But still

```
$ sbt run
...
$ sbt run
...
$ du -sBM /tmp/* | sort -n
...
150M	/tmp/sbt_65105098
150M	/tmp/sbt_bd138339
```

**Comment by cuzfrog** [comment]
> Disabling sbt-tmpfs plugin

How did you do that? From what I remember, you need to remove it or comment it out.

**Comment by arbitrary-dev** [comment]
>How did you do that?
Just commented it out:
```
$ cat ~/.sbt/1.0/plugins/tmpfs.sbt
// addSbtPlugin("com.github.cuzfrog" % "sbt-tmpfs" % "0.3.4")
```

Maybe something is cached somewhere...

**Comment by cuzfrog** [comment]
I would recommend using plugins project-wise. Once the plugins is disabled, re-entering into sbt console will not have it working. Files in `/tmp` will be removed after a restart.
